"""Convert extracted PCB wiring into G-code for a pen-plotter / drawing machine.

Flow:  KiCad file  ->  pcb_read.wiring_data  ->  G-code  ->  GRBL/FluidNC

Each track segment becomes a pen-up travel to its start, a pen-down, a draw
to its end, then a pen-up. Coordinates are passed straight through in mm.

This targets a SINGLE-LAYER plot by default (front copper), which is the
common case for the mini / hobby projects this tool is aimed at.
"""
from pcb_read import wiring_data

# ---- Machine configuration (edit to match your plotter) --------------------
CONFIG = {
    "pen_up_z": 5.0,        # Z height with pen lifted (mm)
    "pen_down_z": 0.0,      # Z height with pen touching the surface (mm)
    "travel_feed": 3000,    # speed for pen-up moves (mm/min)
    "draw_feed": 800,       # speed while drawing (mm/min)
    "flip_y": False,        # set True if your machine's Y is inverted vs KiCad
    "layer": "F.Cu",        # which copper layer to plot ("F.Cu", "B.Cu", or None for all)
    "optimize": True,       # reorder tracks to minimise pen-up travel
}


def _y(y):
    return -y if CONFIG["flip_y"] else y


def _dist(a, b):
    return ((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2) ** 0.5


def optimize_order(tracks, start=(0.0, 0.0)):
    """Greedy nearest-neighbour ordering with endpoint flipping.

    Returns a list of (start, end) pairs oriented so each trace begins at the
    endpoint nearest the pen's current position, minimising pen-up travel.
    """
    remaining = list(tracks)
    pos = start
    ordered = []
    while remaining:
        best_i, best_d, best_flip = 0, float("inf"), False
        for i, r in enumerate(remaining):
            ds = _dist(pos, r["start"])
            de = _dist(pos, r["end"])
            if ds < best_d:
                best_i, best_d, best_flip = i, ds, False
            if de < best_d:
                best_i, best_d, best_flip = i, de, True
        r = remaining.pop(best_i)
        s, e = (r["end"], r["start"]) if best_flip else (r["start"], r["end"])
        ordered.append((s, e))
        pos = e
    return ordered


def travel_distance(pairs, start=(0.0, 0.0)):
    """Total pen-up (travel) distance for an ordered list of (start, end)."""
    pos, total = start, 0.0
    for s, e in pairs:
        total += _dist(pos, s)
        pos = e
    return total


def generate_gcode(data, cfg=CONFIG):
    """Return a list of G-code lines for the given wiring data."""
    up, down = cfg["pen_up_z"], cfg["pen_down_z"]
    tf, df = cfg["travel_feed"], cfg["draw_feed"]

    tracks = [r for r in data if r["type"] == "track"
              and (cfg["layer"] is None or r["layer"] == cfg["layer"])]

    if cfg["optimize"]:
        pairs = optimize_order(tracks)
    else:
        pairs = [(r["start"], r["end"]) for r in tracks]

    lines = [
        "; Generated by pcb_gcode.py",
        f"; layer={cfg['layer']}  tracks={len(tracks)}  optimize={cfg['optimize']}",
        f"; pen-up travel = {travel_distance(pairs):.1f} mm",
        "G21",              # units = millimetres
        "G90",              # absolute positioning
        f"G0 Z{up:g}",      # start with pen up
    ]

    for (x0, y0), (x1, y1) in pairs:
        lines += [
            f"G0 X{x0:g} Y{_y(y0):g} F{tf}",   # travel to start (pen up)
            f"G1 Z{down:g} F{tf}",             # pen down
            f"G1 X{x1:g} Y{_y(y1):g} F{df}",   # draw the trace
            f"G0 Z{up:g}",                     # pen up
        ]

    lines += [
        "G0 X0 Y0 F%d" % tf,   # return home
        "M2",                  # program end
    ]
    return lines


def main():
    lines = generate_gcode(wiring_data)
    out = "labExam.gcode"
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    n_tracks = sum(1 for r in wiring_data if r["type"] == "track"
                   and (CONFIG["layer"] is None or r["layer"] == CONFIG["layer"]))
    print(f"Wrote {out}: {len(lines)} lines, {n_tracks} tracks on layer {CONFIG['layer']}.")


if __name__ == "__main__":
    main()
